Fix unable to find string literal operator error reported by GCC 8.3
In C++11 there is a breaking change that leads to preprocessor tokens
aren't expanded when they are not separated from string literals

Consider the following example

  #define _bar "bar"
  "foo"_bar

Prior to C++11 the 2nd line would have been two tokens. After C++11 it
is now a single token interpreted as a user defined string literal.

GCC 8.3 therefore complains

 np/testmanager.cxx: In member function 'void np::testmanager_t::print_banner()':
 np/testmanager.cxx:80:38: error: inconsistent user-defined literal suffixes '_NP_OS' and '_NP_ARCH' in string literal
      printf("np: Built for O/S "_NP_OS" architecture "_NP_ARCH"\n");
                                       ^~~~~~~~~~~~~~~~~~~~~~~~
 np/testmanager.cxx:80:62: error: unable to find string literal operator 'operator""_NP_OS' with 'const char [34]', 'unsigned int' arguments
      printf("np: Built for O/S "_NP_OS" architecture "_NP_ARCH"\n");
                                                               ^~~~
 cc1plus: all warnings being treated as errors
 Makefile:148: recipe for target 'np/event.o' failed
 make[1]: *** [np/event.o] Error 1
 make[1]: *** Waiting for unfinished jobs....
 np.c: In function 'void be_valground()':
 np.c:62:12: error: unable to find string literal operator 'operator""_NP_VALGRIND_SUPPRESSION_FILE' with 'const char [16]', 'unsigned int' arguments
      *p++ = "--suppressions="_NP_VALGRIND_SUPPRESSION_FILE;
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Avoid the error by adding separating spaces where string concatenation
is intended.

Signed-off-by: Chris Packham <chris.packham@alliedtelesis.co.nz>